//命名：模块名+功能
export const TOKEN_SET = 'TOKEN_SET'
export const TOKEN_CLEAR = 'TOKEN_CLEAR'

export const HISTORY_SEARCH_SET = 'HISTORY_SEARCH_SET'
export const HISTORY_SEARCH_CLEAR = 'HISTORY_SEARCH_CLEAR'

export const FILTER_RULES_SET = 'FILTER_RULES_SET'
export const FILTER_RULES_CLEAR = 'FILTER_RULES_CLEAR'
export const IS_NEED_FILTER_SET = 'IS_NEED_FILTER_SET'